version: 1
title: GitHub Pages
tagline: Your sidekick in using GitHub Pages and blogs
description: Learn how to create a site or blog from your GitHub repositories with GitHub Pages.
tags:
  - GitHub
  - GitHub Pages
template:
  name: "github-pages-with-jekyll"
  url: "https://github.com/githubtraining/github-pages-with-jekyll-template.git"
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 01_class-introduction-issue.md
steps:
  - title: "Enable GitHub Pages"
    description: "Turn on GitHub Pages in your repository."
    event: "deployment_status"
    link: "https://github.com/{{ user.username }}/{{ course.template.name }}/issues/1"
    actions:
      - type: gate
        left: '%payload.deployment_status.state%'
        operator: ===
        right: success
      - type: gate
        left: '%payload.deployment.environment%'
        operator: ===
        right: github-pages
      - type: respond
        issue: 1
        with: 02_update-index.md
        data:
          url: 'https://%user.username%.github.io/%payload.repository.name%'

  - title: "Customize your homepage"
    description: "Open a pull request with changes to the homepage."
    event: "pull_request.opened"
    link: "https://github.com/{{ user.username }}/{{ course.template.name }}/issues"
    actions:
      - type: gate
        left: '%payload.pull_request.body%'
        required: false
        else:
          type: respond
          with: 06a_pull-request-blank.md
      - type: getTree
        action_id: tree
        sha: '%payload.pull_request.head.sha%'
      - type: gate
        gates:
          - left: '%actions.tree.data.tree%'
            operator: includes
            right: 'path:index.html'
          - left: '%actions.tree.data.tree%'
            operator: includes
            right: 'path:index.md'
      - type: createReview
        body: 02r_merge-pr.md
        event: APPROVE
        data:
          branch: '%payload.pull_request.head.ref%'

  - title: "Merge your pull request"
    description: "Merge the pull request that customizes your homepage."
    event: "pull_request.closed"
    link: "https://github.com/{{ user.username }}/{{ course.template.name }}/pulls"
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: gate
        left: '%payload.pull_request.base.ref%'
        operator: ===
        right: 'master'
      - type: getTree
        action_id: tree
        sha: '%payload.pull_request.head.sha%'
      - type: gate
        gates:
          - left: '%actions.tree.data.tree%'
            operator: includes
            right: 'path:index.html'
          - left: '%actions.tree.data.tree%'
            operator: includes
            right: 'path:index.md'
        else:
          type: respond
          with: 02_wrong-file-updated.md
      - type: createIssue
        action_id: issue
        title: Adding a Theme
        body: 03_add-a-theme.md
      - type: closeIssue
        issue: Welcome
      - type: removeBranchProtection
      - type: respond
        with: 04_moving-on-pr.md
        data:
          url: '%actions.issue.data.html_url%'

  - title: "Add a theme"
    description: "Using the theme chooser, select a theme for your site."
    event: "push"
    link: "https://github.com/{{ user.username }}/{{ course.template.name }}/issues"
    actions:
      - type: getFileContents
        action_id: fileContents
        filename: _config.yml
      - type: gate
        left: '/^theme:\s?.+/m'
        operator: test
        right: '%actions.fileContents%'
      - type: updateBranchProtection
      - type: createIssue
        action_id: issue
        title: Getting ready to blog
        body: 05_change-theme.md
      - type: respond
        with: 04_moving-on.md
        issue: Adding a Theme
        data:
          url: '%actions.issue.data.html_url%'
      - type: closeIssue
        issue: Adding a Theme

  - title: "Customize site details"
    description: "Edit the configuration file to display your information."
    event: "pull_request"
    link: "https://github.com/{{ user.username }}/{{ course.template.name }}/issues"
    actions:
      - type: gate
        gates:
          - left: '%payload.action%'
            operator: ===
            right: 'opened'
          - left: '%payload.action%'
            operator: ===
            right: 'synchronize'
      - type: gate
        required: false
        left: '%payload.action%'
        operator: '!=='
        right: 'opened'
        else:
          type: closeIssue
          issue: Getting ready to blog
      - type: gate
        required: false
        left: '%payload.pull_request.body%'
        else:
          type: respond
          with: 06a_pull-request-blank.md
      - type: getFileContents
        filename: _config.yml
        action_id: file
      - type: gate
        left: '%actions.file%'
        operator: test
        right: '/^theme:\s?minima$/m'
        else:
          type: respond
          with: 05r_wrong-theme.md
      - type: respond
        with: 07_create-blog-post.md
        data:
          branch: '%payload.pull_request.head.ref%'

  - title: "Create a blog post"
    description: "Create a new file that will become your first blog post."
    event: "pull_request.synchronize"
    link: "https://github.com/{{ user.username }}/{{ course.template.name }}/pulls"
    actions:
      - type: getTree
        action_id: tree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
      - type: gate
        action_id: directory
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/^_posts/'
      - type: gate
        action_id: filenumber
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/\d{4}-\d{2}-\d{2}/'
      - type: gate
        action_id: post
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/[a-zA-Z]\.md$/'
      - type: gate
        action_id: extension
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/\.md$/'
      - type: gate
        action_id: filename
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: 'path:/^_posts\/(\d{4})-(\d{2})-(\d{2})-(.*)\.md$/'
      - type: gate
        every: true
        gates:
          - left: '%actions.directory%'
          - left: '%actions.filenumber%'
          - left: '%actions.post%'
          - left: '%actions.extension%'
          - left: '%actions.filename%'
        else:
          - type: createReview
            body: 07b_incorrect-post.md
            event: REQUEST_CHANGES
            data:
              directory: '%actions.directory%'
              filenumber: '%actions.filenumber%'
              post: '%actions.post%'
              extension: '%actions.extension%'
              filename: '%actions.filename%'
      - type: createReview
        body: 08_add-front-matter.md
        event: COMMENT

  - title: "Add blog post metadata"
    description: "Add YAML front matter to the blog post to display the title and date."
    event: "pull_request.synchronize"
    link: "https://github.com/{{ user.username }}/{{ course.template.name }}/pulls"
    actions:
      - type: getTree
        action_id: tree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
      - type: findInTree
        action_id: file
        tree: '%actions.tree.data.tree%'
        path: '/^_posts/'
      - type: getFileContents
        filename: '%actions.file.path%'
        action_id: contents
      - type: gate
        required: false
        action_id: dashes
        left: '%actions.contents%'
        operator: test
        right: '/^-{3}[\s\S]+-{3}/'
      - type: gate
        required: false
        action_id: title
        left: '%actions.contents%'
        operator: test
        right: /^title:\s?["'].+["']$/m
      - type: gate
        required: false
        action_id: date
        left: '%actions.contents%'
        operator: test
        right: '/^date:\s?\d{4}-\d{2}-\d{2}/m'
      - type: gate
        every: true
        gates:
          - left: '%actions.dashes%'
          - left: '%actions.title%'
          - left: '%actions.date%'
        else:
          - type: createReview
            body: 08r_incorrect-front-matter.md
            event: REQUEST_CHANGES
            data:
              date: '%actions.date%'
              title: '%actions.title%'
              dashes: '%actions.dashes%'
      - type: createReview
        body: 08_merge-and-celebrate.md
        event: APPROVE

  - title: "Merge your first post"
    description: "Merge the pull request so your blog post will appear on your GitHub Pages site."
    event: "pull_request.closed"
    link: "https://github.com/{{ user.username }}/{{ course.template.name }}/pulls"
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: respond
        with: 10_next-steps.md
        data:
          url: 'https://%user.username%.github.io/%payload.repository.name%'
order: 3
